### ISSUE TITLE
Unresolved metarules_2.11 dependency

### ISSUE THREAD

**Issue by david-simoes-93** [NAMTeam/Network-Addon-Mod#287]
Using Oracle JDK 14 on Linux Ubuntu 20.04.

```
$ ./compileAllMetarules.sh 
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 14.0.1)
[info] loading project definition from /home/david/Downloads/Network-Addon-Mod-master/project
[info] loading settings for project network-addon-mod-master from build.sbt ...
[info] set current project to nam-controller (in build file:/home/david/Downloads/Network-Addon-Mod-master/)
[warn] insecure HTTP request is deprecated 'http://dl.bintray.com/stephenjudkins/maven'; switch to HTTPS or opt-in as ("stephenjudkins-bintray" at "http://dl.bintray.com/stephenjudkins/maven").withAllowInsecureProtocol(true)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.memo33:metarules_2.11:0.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/david/.ivy2/local/com.github.memo33/metarules_2.11/0.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error]   not found: https://googledrive.com/host/0B9r6o2oTyY34ZVc4SFBWMV9yb0E/repo/releases/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error]   not found: http://dl.bintray.com/stephenjudkins/maven/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.memo33:metarules_2.11:0.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/david/.ivy2/local/com.github.memo33/metarules_2.11/0.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error]   not found: https://googledrive.com/host/0B9r6o2oTyY34ZVc4SFBWMV9yb0E/repo/releases/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error]   not found: http://dl.bintray.com/stephenjudkins/maven/com/github/memo33/metarules_2.11/0.1.1/metarules_2.11-0.1.1.pom
[error] Total time: 2 s, completed 03/08/2020, 13:39:38
```

I have access to https://github.com/memo33/metarules by URL, so Iḿ not sure how to debug this. Iḿ not behind any VPN or firewall. Anyone else experiences the same issue?

**Comment by memo33** [comment]
Yes, the problem is that the compiled dependencies are not available anymore. They used to be available from my gdrive, but a couple of years ago Google changed their service so that static hosting is no longer possible, and as a result dependency resolution does not work anymore. This was only meant as a temporary solution, but I have never got around to figuring out an alternative unfortunately. Sorry about that.

It should still be possible to manually compile the dependencies. Though, I have to admit I had difficulties with that myself a while ago, due to backward-incomptabile changes in SBT. Let me attach all the dependencies here instead. They probably need to be extracted into `~/.ivy2/cache/`.

[metarules-dependencies.tar.gz](https://github.com/NAMTeam/Network-Addon-Mod/files/5016955/metarules-dependencies.tar.gz)

Given that there have not been any reports about this problem before, I am not sure if any of this is still in use. I am a bit out of the loop, to be honest.

**Comment by memo33** [comment]
This should be fixed now. I have moved all the dependencies to bintray. Thank you for reporting this.
